# Generated by Django 5.1.7 on 2025-03-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitConverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_unit', models.CharField(max_length=25)),
                ('to_unit', models.CharField(max_length=25)),
                ('value', models.FloatField()),
                ('convert_type', models.CharField(choices=[('Length', 'LENGTH'), ('Weight', 'WEIGHT'), ('Temperature', 'TEMPERATURE')], default='Length', max_length=25)),
                ('result', models.FloatField()),
            ],
        ),
    ]
